use crate::events::{ServerEvent, persist_message, preview_text};
use crate::state::AppState;
use futures::FutureExt;
use jossie_core::integration::{CapabilityGroup, IntegrationRegistry, ToolEffect, tool_metadata};
use jossie_core::types::{Message, Role};
use jossie_db::{IntegrationEvent, MemoryEntry, MemoryPromptEntry, NewPendingAction};
use regex::Regex;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
use std::panic::AssertUnwindSafe;
use std::sync::Arc;
use std::time::Duration;
use uuid::Uuid;

include!("agent/goal_tracking.rs");
include!("agent/prompt_context.rs");
include!("agent/tools.rs");
include!("agent/run.rs");
include!("agent/streaming.rs");
include!("agent/reflection_knowledge.rs");
include!("agent/event_mode.rs");
include!("agent/context_window.rs");
include!("agent/tests.rs");
include!("agent/knowledge_models.rs");
