/// Self-reflection: evaluate response quality using kg_llm.
/// Returns Some(feedback) if the response should be retried, None if it's acceptable.
async fn self_reflect(
    state: &AppState,
    recent_messages: &[Message],
    user_message: &str,
    assistant_response: &str,
) -> Option<String> {
    let recent_context = build_reflection_context(recent_messages);
    let prompt = format!(
        r#"Evaluate the quality of this assistant response to the user's message.

Recent conversation context:
{recent_context}

User message: {user_message}

Assistant response: {assistant_response}

Evaluate on these criteria:
1. Does it actually answer the user's question/request?
2. Is information accurate and complete?
3. Does it preserve the current conversational stance instead of resetting into generic assistant voice?
4. Is it specific, direct, and naturally warm when appropriate?
5. Does it avoid stock empathy, unnecessary hedging, obvious restatements, and balanced-but-vague filler?
6. Does it take a useful next step or name one when the user's goal is not finished?
7. Does it handle uncertainty with evidence instead of guessing?

Respond with EXACTLY one of:
- "PASS" if the response is acceptable
- "RETRY: <specific feedback>" if the response needs improvement

Output only PASS or RETRY: <feedback>, nothing else."#
    );

    let sys = Message::transient(
        Role::System,
        "You are a response quality evaluator. Be concise.".to_string(),
    );
    let user = Message::transient(Role::User, prompt);

    match state.kg_llm.complete(&[sys, user], &[]).await {
        Ok(output) => {
            let verdict = output.content;
            let trimmed = verdict.trim();
            if trimmed.starts_with("RETRY:") {
                let feedback = trimmed.strip_prefix("RETRY:").unwrap_or("").trim();
                tracing::info!("Self-reflection: retry recommended. Feedback: {feedback}");
                Some(feedback.to_string())
            } else {
                tracing::debug!("Self-reflection: response passed quality check");
                None
            }
        }
        Err(e) => {
            tracing::warn!("Self-reflection failed: {e}. Proceeding with original response.");
            None
        }
    }
}

async fn persist_final_assistant_response(
    state: &AppState,
    conv_id: Uuid,
    user_message: String,
    assistant_reply: String,
) -> anyhow::Result<()> {
    persist_message(
        state,
        &Message::new(conv_id, Role::Assistant, assistant_reply.clone()),
    )
    .await?;

    let db = state.db.clone();
    let kg_llm = state.kg_llm.clone();
    let openai_optimizations = state.openai_optimizations;
    tokio::spawn(async move {
        spawn_knowledge_extraction(
            db,
            kg_llm,
            user_message,
            assistant_reply,
            openai_optimizations,
        )
        .await;
    });

    let summary_db = state.db.clone();
    let summary_llm = state.kg_llm.clone();
    tokio::spawn(async move {
        update_rolling_conversation_summary(summary_db, summary_llm, conv_id).await;
    });
    Ok(())
}

/// Context compression: summarize older messages when context exceeds threshold.
/// Keeps the most recent `keep_recent` messages in full and replaces older ones
/// with a compact summary generated by kg_llm.
async fn maybe_summarize_context(state: &AppState, conv_id: Uuid, messages: &mut Vec<Message>) {
    let total_chars: usize = messages.iter().map(|m| m.content.len()).sum();
    let keep_recent = state.context_keep_recent_dialogue_messages;

    let existing_summary = state
        .db
        .get_conversation_summary(conv_id)
        .await
        .ok()
        .flatten();
    if let Some(existing) = &existing_summary
        && !messages
            .iter()
            .any(|message| message.name.as_deref() == Some("conversation_summary"))
    {
        messages.insert(
            0,
            Message::transient(
                Role::System,
                format!(
                    "## Conversation Continuity Summary (previous {} messages)\nUse this to preserve facts, relationship continuity, and conversational stance.\n{}",
                    existing.messages_summarized, existing.summary
                ),
            )
            .with_name("conversation_summary".to_string()),
        );
    }

    if total_chars < state.max_context_chars || messages.len() <= keep_recent {
        return;
    }

    tracing::info!(
        "Context size ({} chars, {} messages) exceeds threshold. Attempting summarization.",
        total_chars,
        messages.len()
    );

    // Check if we already have a recent summary
    if let Some(existing) = existing_summary {
        // If we already summarized most messages, just use the existing summary
        let unsummarized = messages.len() as i64 - existing.messages_summarized;
        if unsummarized <= keep_recent as i64 + 5 {
            // Inject existing summary and keep only recent messages
            let keep_from = messages.len().saturating_sub(keep_recent);
            let mut recent = messages.split_off(keep_from);
            sanitize_context_window(&mut recent);
            messages.clear();
            messages.push(Message::transient(
                Role::System,
                format!(
                    "## Conversation Continuity Summary (previous {} messages)\nUse this to preserve facts, relationship continuity, and conversational stance.\n{}",
                    existing.messages_summarized, existing.summary
                ),
            ).with_name("conversation_summary".to_string()));
            messages.extend(recent);
            return;
        }
    }

    // Build the older messages to summarize
    let keep_from = messages.len().saturating_sub(keep_recent);
    let to_summarize: Vec<String> = messages[..keep_from]
        .iter()
        .map(|m| format!("{:?}: {}", m.role, &m.content[..m.content.len().min(500)]))
        .collect();

    if to_summarize.is_empty() {
        return;
    }

    let summarize_text = to_summarize.join("\n---\n");
    let prompt = format!(
        r#"Summarize the following conversation history into a compact continuity summary.
Preserve: key facts, decisions made, tool results, ongoing goals, commitments, unresolved blockers, next actions, user preferences about how to be helped, the current conversational stance, and any recent style corrections the assistant should remember.
Omit: pleasantries, redundant information, and tool call arguments.
Do not invent motives, emotions, or certainty that are not grounded in the conversation.
Be concise but complete.
Output short markdown with exactly these sections:
## Facts And Decisions
## User Preferences And Relationship Signals
## Current Stance To Preserve
## Open Loops

Conversation:
{summarize_text}"#
    );

    let sys = Message::transient(
        Role::System,
        "You are a conversation summarizer. Output a concise summary.".to_string(),
    );
    let user = Message::transient(Role::User, prompt);

    match state.kg_llm.complete(&[sys, user], &[]).await {
        Ok(output) => {
            let summary = output.content;
            let messages_count = keep_from as i64;
            let last_id = messages
                .get(keep_from.saturating_sub(1))
                .map(|m| m.id.to_string());
            let _ = state
                .db
                .save_conversation_summary(conv_id, &summary, messages_count, last_id.as_deref())
                .await;

            let mut recent = messages.split_off(keep_from);
            sanitize_context_window(&mut recent);
            messages.clear();
            messages.push(Message::transient(
                Role::System,
                format!(
                    "## Conversation Continuity Summary (previous {} messages)\nUse this to preserve facts, relationship continuity, and conversational stance.\n{}",
                    messages_count, summary
                ),
            ).with_name("conversation_summary".to_string()));
            messages.extend(recent);

            tracing::info!(
                "Summarized {} messages into {} chars. New context: {} messages.",
                messages_count,
                summary.len(),
                messages.len()
            );
        }
        Err(e) => {
            tracing::warn!("Failed to summarize context: {e}. Continuing with full context.");
        }
    }
}

async fn update_rolling_conversation_summary(
    db: Arc<jossie_db::Database>,
    kg_llm: jossie_llm::LlmClient,
    conversation_id: Uuid,
) {
    const SUMMARY_CHUNK_MESSAGES: usize = 120;
    const SUMMARY_MIN_MESSAGES: usize = 80;
    const SUMMARY_MIN_CHARS: usize = 40_000;

    let existing = db
        .get_conversation_summary(conversation_id)
        .await
        .ok()
        .flatten();
    let last_message_id = existing
        .as_ref()
        .and_then(|summary| summary.last_message_id.as_deref());
    let Ok(chunk) = db
        .get_messages_after_for_summary(conversation_id, last_message_id, SUMMARY_CHUNK_MESSAGES)
        .await
    else {
        return;
    };
    let chunk_chars = chunk
        .iter()
        .map(|message| message.content.len())
        .sum::<usize>();
    if chunk.len() < SUMMARY_MIN_MESSAGES && chunk_chars < SUMMARY_MIN_CHARS {
        return;
    }
    let _ = db
        .upsert_worker_status(
            "conversation_summary",
            "Conversation summaries",
            "running",
            None,
            Some("Updating conversation continuity"),
            false,
            None,
        )
        .await;

    let transcript = chunk
        .iter()
        .map(|message| {
            let content = if message.role == Role::Tool {
                preview_text(&message.content, 800)
            } else {
                preview_text(&message.content, 1_500)
            };
            format!("{:?}: {content}", message.role)
        })
        .collect::<Vec<_>>()
        .join("\n---\n");
    let previous = existing
        .as_ref()
        .map(|summary| summary.summary.as_str())
        .unwrap_or("No previous summary.");
    let prompt = format!(
        "Update the compact conversation continuity summary using the new transcript chunk.\n\
         Preserve durable facts, decisions, user preferences, commitments, unresolved blockers,\n\
         important tool findings, current conversational stance, and next actions. Remove stale or\n\
         superseded details. Do not invent facts. Return concise markdown with exactly these headings:\n\
         ## Facts And Decisions\n## User Preferences And Relationship Signals\n\
         ## Current Stance To Preserve\n## Open Loops\n\n\
         Previous summary:\n{previous}\n\nNew transcript chunk:\n{transcript}"
    );
    let system = Message::transient(
        Role::System,
        "You maintain compact rolling conversation state. Output only the requested summary."
            .to_string(),
    );
    let user = Message::transient(Role::User, prompt);
    match kg_llm.complete(&[system, user], &[]).await {
        Ok(output) if !output.content.trim().is_empty() => {
            let previous_count = existing
                .as_ref()
                .map(|summary| summary.messages_summarized)
                .unwrap_or(0);
            let last_id = chunk.last().map(|message| message.id.to_string());
            if let Err(error) = db
                .save_conversation_summary(
                    conversation_id,
                    &output.content,
                    previous_count + chunk.len() as i64,
                    last_id.as_deref(),
                )
                .await
            {
                tracing::warn!("Failed to save rolling conversation summary: {error}");
                let _ = db
                    .upsert_worker_status(
                        "conversation_summary",
                        "Conversation summaries",
                        "degraded",
                        None,
                        Some("Latest summary failed"),
                        false,
                        Some(&error.to_string()),
                    )
                    .await;
            } else {
                let _ = db
                    .upsert_worker_status(
                        "conversation_summary",
                        "Conversation summaries",
                        "idle",
                        None,
                        Some("Ready"),
                        true,
                        None,
                    )
                    .await;
            }
        }
        Ok(_) => {
            let _ = db
                .upsert_worker_status(
                    "conversation_summary",
                    "Conversation summaries",
                    "idle",
                    None,
                    Some("No summary update was needed"),
                    true,
                    None,
                )
                .await;
        }
        Err(error) => {
            tracing::warn!("Rolling conversation summary failed: {error}");
            let _ = db
                .upsert_worker_status(
                    "conversation_summary",
                    "Conversation summaries",
                    "degraded",
                    None,
                    Some("Latest summary failed"),
                    false,
                    Some(&error.to_string()),
                )
                .await;
        }
    }
}

pub(crate) async fn spawn_knowledge_extraction(
    db: Arc<jossie_db::Database>,
    kg_llm: jossie_llm::LlmClient,
    user_msg: String,
    assistant_msg: String,
    openai_optimizations: bool,
) {
    if !should_extract_knowledge(&user_msg, &assistant_msg) {
        tracing::debug!("Skipping knowledge extraction for a low-signal turn");
        return;
    }
    let _ = db
        .upsert_worker_status(
            "knowledge_extraction",
            "Knowledge extraction",
            "running",
            None,
            Some("Reviewing a completed conversation turn"),
            false,
            None,
        )
        .await;

    let prompt = format!(
        r#"Extract knowledge from this conversation turn.
Identify Entities (people, projects, concepts) and Relationships.
Ignore trivial chit-chat.
Only extract information grounded in the turn. Do not infer private facts, emotions, or relationships that are not stated.
Use stable lowercase IDs and merge obvious aliases to the same ID.

User: {user_msg}
Assistant: {assistant_msg}

Output ONLY valid JSON matching this structure:
{{
  "nodes": [
    {{ "id": "unique_id_lowercase", "label": "Display Name", "type": "Category" }}
  ],
  "edges": [
    {{ "source": "id_source", "target": "id_target", "relation": "RELATION_TYPE" }}
  ]
}}
If nothing to extract, output {{ "nodes": [], "edges": [] }}"#
    );

    let sys_msg = Message::transient(
        Role::System,
        "You are a Knowledge Graph Extractor. Output strictly JSON.".to_string(),
    );
    let user_msg = Message::transient(Role::User, prompt);

    let extraction_messages = [sys_msg, user_msg];
    let extraction_result = if openai_optimizations {
        kg_llm
            .complete_with_options(
                &extraction_messages,
                &[],
                &jossie_llm::LlmRequestOptions {
                    structured_output: Some(jossie_llm::StructuredOutputFormat {
                        name: "knowledge_graph_extraction".to_string(),
                        schema: serde_json::json!({
                            "type": "object",
                            "properties": {
                                "nodes": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {"type": "string"},
                                            "label": {"type": "string"},
                                            "type": {"type": "string"}
                                        },
                                        "required": ["id", "label", "type"],
                                        "additionalProperties": false
                                    }
                                },
                                "edges": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "source": {"type": "string"},
                                            "target": {"type": "string"},
                                            "relation": {"type": "string"}
                                        },
                                        "required": ["source", "target", "relation"],
                                        "additionalProperties": false
                                    }
                                }
                            },
                            "required": ["nodes", "edges"],
                            "additionalProperties": false
                        }),
                    }),
                    ..jossie_llm::LlmRequestOptions::default()
                },
            )
            .await
    } else {
        kg_llm.complete(&extraction_messages, &[]).await
    };
    match extraction_result {
        Ok(output) => {
            let response = output.content;
            let clean_json = response
                .trim()
                .trim_start_matches("```json")
                .trim_end_matches("```");
            match serde_json::from_str::<ExtractionResult>(clean_json) {
                Ok(data) => {
                    let node_count = data.nodes.len();
                    let edge_count = data.edges.len();
                    for node in &data.nodes {
                        let _ = db
                            .graph_upsert_node(
                                &node.id,
                                &node.label,
                                &node.node_type,
                                &serde_json::json!({}),
                            )
                            .await;
                    }
                    for edge in &data.edges {
                        let _ = db
                            .graph_upsert_edge(
                                &edge.source,
                                &edge.target,
                                &edge.relation,
                                1.0,
                                &serde_json::json!({}),
                            )
                            .await;
                    }
                    if node_count > 0 || edge_count > 0 {
                        tracing::info!("Extracted {} nodes and {} edges", node_count, edge_count);
                    }
                    let _ = db
                        .upsert_worker_status(
                            "knowledge_extraction",
                            "Knowledge extraction",
                            "idle",
                            None,
                            Some("Ready"),
                            true,
                            None,
                        )
                        .await;
                }
                Err(e) => {
                    tracing::warn!("Failed to parse KG extraction JSON: {e}");
                    let _ = db
                        .upsert_worker_status(
                            "knowledge_extraction",
                            "Knowledge extraction",
                            "degraded",
                            None,
                            Some("Latest extraction could not be read"),
                            false,
                            Some(&e.to_string()),
                        )
                        .await;
                }
            }
        }
        Err(e) => {
            tracing::error!("KG Extraction LLM failed: {e}");
            let _ = db
                .upsert_worker_status(
                    "knowledge_extraction",
                    "Knowledge extraction",
                    "degraded",
                    None,
                    Some("Latest extraction failed"),
                    false,
                    Some(&e.to_string()),
                )
                .await;
        }
    }
}

fn should_extract_knowledge(user_msg: &str, assistant_msg: &str) -> bool {
    if user_msg.trim().len() + assistant_msg.trim().len() < 80 {
        return false;
    }
    let combined = format!("{user_msg}\n{assistant_msg}");
    let lower = combined.to_lowercase();
    let has_durable_relation = contains_any(
        &lower,
        &[
            " works at ",
            " works on ",
            " lives in ",
            " is my ",
            " project ",
            " company ",
            " colleague ",
            " friend ",
            " partner ",
            " manager ",
            " meeting with ",
        ],
    );
    let has_explicit_identifier = user_msg.contains('@') || user_msg.contains('"');
    let has_entity_context = contains_any(
        &user_msg.to_lowercase(),
        &[
            "person",
            "people",
            "project",
            "company",
            "colleague",
            "friend",
            "partner",
            "manager",
            "boss",
            "family",
            "meeting",
            "works",
            "lives",
        ],
    );
    has_durable_relation
        || has_explicit_identifier
        || (has_entity_context && !extract_candidate_entities(user_msg).is_empty())
}
