[package]
name = "jossie-integration-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
jossie-core = { workspace = true }
headless_chrome = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
scraper = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
schemars = { workspace = true }
