[package]
name = "jossie-integration-browser"
version = "0.1.0"
edition = "2024"

[dependencies]
jossie-core = { workspace = true }
jossie-db = { workspace = true } # Might need this if we store history, otherwise optional
headless_chrome = { workspace = true }
html2text = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
scraper = { workspace = true }
url = "2.5"
tokio = { workspace = true }
uuid = { workspace = true }
