use std::path::PathBuf;
use ts_rs::TS;

fn declaration<T: TS>(config: &ts_rs::Config) -> String {
    format!("export {}\n\n", T::decl(config))
}

fn generated_contracts() -> String {
    let config = ts_rs::Config::default().with_large_int("number");
    let mut output = String::from(concat!(
        "// Generated by `cargo run -p xtask -- generate-types`. Do not edit.\n\n",
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };\n\n",
    ));

    macro_rules! export_types {
        ($($type:ty),+ $(,)?) => {
            $(output.push_str(&declaration::<$type>(&config));)+
        };
    }

    export_types!(
        jossie_core::types::Role,
        jossie_core::types::Attachment,
        jossie_core::types::Message,
        jossie_core::types::Conversation,
        jossie_core::integration::ToolCall,
        jossie_core::integration::OnboardingField,
        jossie_core::integration::OnboardingStatus,
        jossie_db::ConversationListItem,
        jossie_db::ChatImport,
        jossie_db::GraphNode,
        jossie_db::GraphEdge,
        jossie_db::MemoryEntryWithMetadata,
        jossie_db::ActivityEvent,
        jossie_db::PendingAction,
        jossie_db::ScheduledTask,
        jossie_db::Goal,
        jossie_db::GoalTask,
        jossie_db::GoalWithTasks,
        jossie_db::WorkRun,
        jossie_db::WorkRunStep,
        jossie_db::WorkRunDetail,
        jossie_db::WorkerStatus,
        jossie_server::handlers::dashboard::DashboardStats,
        jossie_server::handlers::dashboard::GraphHighlight,
        jossie_server::handlers::dashboard::DashboardResponse,
        jossie_server::handlers::work::WorkSummary,
        jossie_server::handlers::work::GoalDetail,
        jossie_server::handlers::integrations::IntegrationStatus,
        jossie_server::handlers::config::AccountConfig,
        jossie_server::ServerEvent,
    );

    output
}

fn main() {
    let mut args = std::env::args().skip(1);
    if args.next().as_deref() != Some("generate-types") {
        eprintln!("usage: cargo run -p xtask -- generate-types [--check]");
        std::process::exit(2);
    }
    let check = args.any(|arg| arg == "--check");
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../frontend/src/generated/contracts.ts");
    let generated = generated_contracts();

    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current != generated {
            eprintln!(
                "{} is stale; run `cargo run -p xtask -- generate-types`",
                path.display()
            );
            std::process::exit(1);
        }
        return;
    }

    std::fs::create_dir_all(path.parent().expect("generated directory"))
        .expect("create generated directory");
    std::fs::write(&path, generated).expect("write generated contracts");
}
